# Generated by Django 3.1.5 on 2021-01-18 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stonk_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='current_price',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='holding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='stonk_portfolio.portfolio'),
        ),
    ]
