# Generated by Django 3.1.5 on 2021-01-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stonk_portfolio', '0002_auto_20210118_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='exchange',
            field=models.CharField(default='NASDAQ', max_length=10),
            preserve_default=False,
        ),
    ]
