# Generated by Django 3.1.5 on 2021-01-24 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stonk_portfolio', '0003_stock_exchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='value',
        ),
    ]
